services:
  - type: web
    name: stakeholder-management-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot_web.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 